version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - rabbitmq_network

  producer:
    build: ./producer
    ports:
      - "5000:5000"
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_one:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_two:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_three:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_four:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  database:
    networks:
      - microservices_network
  
networks:
  rabbitmq_network:
  microservices_network:
